/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-04-27 09:10:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sk.metier.*;

public final class pageCV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Identification Administrateur</title>\r\n");
      out.write("    <link href=\"http://www.activconsult-ing.com/Home.css\" rel=\"stylesheet\"\r\n");
      out.write("        type=\"text/css\">\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("#formationLyon {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 5px;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    height: 600px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, td, th {\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    border-spacing: 0px;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rTable {\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".rTableCompetence {\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 70%;\r\n");
      out.write("}\r\n");
      out.write(".rTableHeading, .rTableBody, .rTableFoot, .rTableRow{\r\n");
      out.write("      clear: both;\r\n");
      out.write("}\r\n");
      out.write(".rTableHead, .rTableFoot{\r\n");
      out.write("      background-color: #DDD;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".rTableCell, .rTableHead {\r\n");
      out.write("      border: 1px solid #999999;\r\n");
      out.write("      float: left;\r\n");
      out.write("      height: 17px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      padding: 3px 0;\r\n");
      out.write("      width: 28%;\r\n");
      out.write("}\r\n");
      out.write(".rTable:after {\r\n");
      out.write("       visibility: hidden;\r\n");
      out.write("       display: block;\r\n");
      out.write("       font-size: 0;\r\n");
      out.write("       content: \" \";\r\n");
      out.write("       clear: both;\r\n");
      out.write("       height: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#info2 {\r\n");
      out.write("    width:700px;\r\n");
      out.write("    height:500px;\r\n");
      out.write("}\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"background\">\r\n");
      out.write("        <div id=\"back2\">\r\n");
      out.write("            <img src=\"http://www.activconsult-ing.com/img/Article_fond_bleu.png\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"back3\">\r\n");
      out.write("            <img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/shutterstock_106416164.png\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/index.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/ACI_Logo_quadri_blanc.png\"\r\n");
      out.write("                width=\"184\" height=\"185\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"white\">\r\n");
      out.write("            <img src=\"http://www.activconsult-ing.com/img/Article_fond_blanc.png\"\r\n");
      out.write("                width=\"782\" height=\"595\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo1\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/qui_sommes_nous.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_ancre.png\"\r\n");
      out.write("                alt=\"Qui sommes nous ?\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo2\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/le_groupe.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_poulpe.png\" width=\"70\"\r\n");
      out.write("                height=\"93\" alt=\"Le groupe\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo3\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/centre_formation.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_pagaies.png\"\r\n");
      out.write("                width=\"71\" height=\"103\" alt=\"Centre de formation\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo4\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/nos_offres1.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_rose_des_vents.png\"\r\n");
      out.write("                width=\"71\" height=\"93\" alt=\"Nos offres\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo5\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/domaines_activites.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_noeuds.png\" width=\"72\"\r\n");
      out.write("                height=\"103\" alt=\"Domaines d'activitÃ©s\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo6\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/recrutement_rh.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_capitaine.png\"\r\n");
      out.write("                width=\"71\" height=\"103\" alt=\"Recrutement RH\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo8\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/ressources_externes.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_bouÃ©e.png\" width=\"71\"\r\n");
      out.write("                height=\"103\" alt=\"Ressouces externes\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logo7\">\r\n");
      out.write("            <a href=\"http://www.activconsult-ing.com/contact.html\"><img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Menu_gouvernail.png\"\r\n");
      out.write("                width=\"71\" height=\"93\" alt=\"Contact\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"titre1\">ENTREPRISE DE SERVICES DU NUMERIQUE</div>\r\n");
      out.write("        <div id=\"menu3\">\r\n");
      out.write("            <img\r\n");
      out.write("                src=\"http://www.activconsult-ing.com/img/Objet_dynamique_vectoriel.png\"\r\n");
      out.write("                width=\"342\" height=\"57\" alt=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"logol1\">\r\n");
      out.write("            <img src=\"http://www.activconsult-ing.com/img/Menu_pagaies2.png\"\r\n");
      out.write("                width=\"71\" height=\"71\" alt=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"tlogo\">CENTRE DE FORMATION</div>\r\n");
      out.write("        <div id=\"info2\">\r\n");
      out.write("        ");

        Formation formation = (Formation) session.getAttribute("formation");
        String sSel=request.getParameter("boutonEtudiant");
        ListeEtudiant listeEtudiant = formation.getListeEtudiant();
        Etudiant etudiant = listeEtudiant.get(Integer.valueOf(sSel).intValue());
      
        
      out.write("\r\n");
      out.write("       \r\n");
      out.write("            <div style=\"position: absolute;top: -105px;left: 320px;\"><h1 style=\"color:blue;\">CV</h2></div>\r\n");
      out.write("            <div style=\"position: absolute;top: -85px;left: 340px;\"><h2 style=\"color:blue;\">");
      out.print( etudiant.getNom() );
      out.write("</h2></div>\r\n");
      out.write("            <div style=\"position: absolute;top: -65px;left: 340px;\"><h2 style=\"color:blue;\">");
      out.print( etudiant.getPrenom());
      out.write("</h2></div>\r\n");
      out.write("            <div style=\"position: absolute;top: -35px;left: 360px;\"><p>");
      out.print( etudiant.getEmail());
      out.write("</p></div>\r\n");
      out.write("            <div id=\"formationLyon\">\r\n");
      out.write("                <div style=\"width:500px; height:200px;overflow:auto\">\r\n");
      out.write("                    <h3>CompÃ©tences</h3>\r\n");
      out.write("                    <div class=\"rTable\">\r\n");
      out.write("                  \r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:20%\"><strong>Type</strong></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:39%\"><span style=\"font-weight: bold;\">PrÃ©cision</span></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:39%\">Niveau</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      ");
      out.print( etudiant.getListeCompetence().size());
      out.write("\r\n");
      out.write("                        ");
 for (int i=0; i<etudiant.getListeCompetence().size();i++) {
                        Competence competence = etudiant.getListeCompetence().get(i);
      out.write("\r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:20%\">");
      out.print( competence.getType());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:39%\">");
      out.print( competence.getDetail());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:39%\">");
      out.print( competence.getNiveau());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"width:700px; height:200px;overflow:auto\">\r\n");
      out.write("                    <h3>ExpÃ©riences</h3>\r\n");
      out.write("                    <div class=\"rTable\">\r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:20%\"><strong>Date</strong></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:20%\"><span style=\"font-weight: bold;\">Entreprise</span></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:20%\">Poste</div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:38%\">Description</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 for (int i=0; i<etudiant.getListeExperience().size();i++){
                            Experience experience = etudiant.getListeExperience().get(i);                          
                            
      out.write("                      \r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:20%\">");
      out.print( experience.getDateExp());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:20%\">");
      out.print( experience.getEntreprise());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:20%\">");
      out.print( experience.getPoste());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:38%\">");
      out.print( experience.getDescription());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"width:700px; height:200px;overflow:auto\">\r\n");
      out.write("                    <h3>Formations</h3>\r\n");
      out.write("                    <div class=\"rTable\">\r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:20%\"><strong>Date</strong></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:39%\"><span style=\"font-weight: bold;\">DiplÃ´me</span></div>\r\n");
      out.write("                            <div class=\"rTableHead\" style=\"width:39%\">Ecole</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 for (int i=0; i < etudiant.getListeFormationScolaire().size(); i++) {
                        FormationScolaire formationScolaire = etudiant.getListeFormationScolaire().get(i);
                      
                        
      out.write("\r\n");
      out.write("                        <div class=\"rTableRow\">\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:20%\">");
      out.print( formationScolaire.getDate());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:39%\">");
      out.print( formationScolaire.getDiplome());
      out.write("</div>\r\n");
      out.write("                            <div class=\"rTableCell\" style=\"width:39%\">");
      out.print( formationScolaire.getEcole());
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"fpage2\">\r\n");
      out.write("            <img src=\"http://www.activconsult-ing.com/img/Article_fond_blanc_double_copie.png\" />\r\n");
      out.write("            <div id=\"Facebook2\">\r\n");
      out.write("                <img src=\"http://www.activconsult-ing.com/img/Facebook.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"linkedin2\">\r\n");
      out.write("                <img src=\"http://www.activconsult-ing.com/img/Linkedin.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"viadeo2\">\r\n");
      out.write("                <img src=\"http://www.activconsult-ing.com/img/Viadeo.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"droit2\">Â©1997-2012 - Tous droits de reproduction et de\r\n");
      out.write("                reprÃ©sentation rÃ©servÃ©s Mentions lÃ©gales</div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
